<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-maccatalyst</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>WindowManager.MacOS</AssemblyName>
    <RootNamespace>WindowManager.MacOS</RootNamespace>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WindowManager.Abstractions\WindowManager.Abstractions.csproj" />
  </ItemGroup>
</Project>
